### ISSUE TITLE
Dockerfile creates its own instance of MySQL database

### ISSUE THREAD

**Issue by naclcaleb** [highlowapp/Backend#1]
Right now, it looks like the Dockerfile is installing its own mysql server. However, in reality, the Docker image for the backend doesn't need to host a MySQL server. 

We will be hosting the website on one of Bluehost's servers, which already have MySQL server installed. 

Our docker image will instead need to have MySQL client (via the Python MySQLdb package). That way, if our docker image needs to be moved, we won't lose all our data.

I can make some drawings of my imagined architecture if you'd like.

**Comment by Redemption777** [comment]
It looks like it is fixed now.

**Comment by naclcaleb** [comment]
👍
