### ISSUE TITLE
Dockerfile git clone of highlow points to an invalid URL

### ISSUE THREAD

**Issue by naclcaleb** [highlowapp/Backend#2]
Currently the Dockerfile on the master branch has a `RUN git clone https://github.com/highlowapp`, but that is the URL for the organization, not a specific repository. Perhaps it was supposed to be `git clone https://github.com/highlowapp/Backend` ?

**Comment by Redemption777** [comment]
Yes sorry I forgot that, thanks!

**Comment by naclcaleb** [comment]
Welcome, just making sure!

It might have worked anyway, I just wasn't sure.
